# Generated by Django 3.0.3 on 2020-02-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20200229_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
