# Generated by Django 3.0.3 on 2020-02-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20200229_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='booklist',
            name='img',
            field=models.ImageField(upload_to='book_picture'),
        ),
    ]
