# Generated by Django 3.0.3 on 2020-03-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_id', models.IntegerField()),
                ('member_name', models.CharField(max_length=50)),
                ('member_id', models.IntegerField()),
            ],
        ),
    ]
