# Generated by Django 3.0.3 on 2020-03-01 19:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_app', '0006_loanlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanlist',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='loanlist',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='loanlist',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='loanlist',
            name='member_name',
        ),
        migrations.AddField(
            model_name='loanlist',
            name='book',
            field=models.ManyToManyField(to='library_app.BookList'),
        ),
        migrations.AddField(
            model_name='loanlist',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
