# Generated by Django 3.0.3 on 2020-03-01 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_loanlist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
