# Generated by Django 3.0.3 on 2020-03-01 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_app', '0009_loanlist_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanlist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='loanlist',
            name='status',
        ),
        migrations.AlterField(
            model_name='loanlist',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, to='library_app.BookList'),
        ),
        migrations.AlterField(
            model_name='loanlist',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
