# Generated by Django 3.0.3 on 2020-03-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0017_auto_20200305_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookloan',
            name='order',
            field=models.BooleanField(default=False),
        ),
    ]
