# Generated by Django 3.0.3 on 2020-03-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0019_auto_20200305_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookloan',
            name='ordered',
        ),
    ]
